# Generated by Django 5.2.5 on 2025-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='optimized_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/optimized/'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/thumbnails/'),
        ),
    ]
