# Generated by Django 5.2.5 on 2026-08-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_booking_payment_date_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_transaction_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=100),
        ),
    ]
